# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd23723f0d77eb8ac6c2d0182e3e5cf495250d3564da3950dec0364b696fa20f251fead88abf3fa1c05a2b8c5bd16e732dd536232757eb9dce4d6a45f306d82

test:
  secret_key_base: a7562cec117b9b6f826b8bfe95046b5cabda47d15aa243b3e037f1a90bc1d20fcc5b6abc21c74979157467b82d9236d8e693b242d8da585da96a896a1e2f8add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
